### ISSUE TITLE
Check if process is running before killing

### ISSUE THREAD

**Issue by mikeobrien** [abnerdasdores/iisexpress-bootstrapper#10]
For some reason I just started getting the following error in my test suite tear down method.

![image](https://cloud.githubusercontent.com/assets/187817/16347619/bc4d18d2-3a1b-11e6-8a30-ba486485303f.png)

No idea why/how the IIS process is terminating before it hits dispose but wonder if it would be a good idea anyways to check if the process is still running before [killing it](https://github.com/abnerdasdores/iisexpress-bootstrapper/blob/master/src/IISExpressBootstrapper/ProcessRunner.cs#L42)? If so, I can submit a PR.

**Comment by abnerdasdores** [comment]
I think it's a good idea. I'll wait the PR. (:

**Comment by mikeobrien** [comment]
Great, thx, just submitted! Thx for this lib BTW, it's been fantastic!

**Comment by mikeobrien** [comment]
Just updated and works like a chanpeen! Thx!
